// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CalendarController from "./calendar_controller"
application.register("calendar", CalendarController)

import CalendarDatePickerController from "./calendar_date_picker_controller"
application.register("calendar-date-picker", CalendarDatePickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
